### ISSUE TITLE
Removing old conferences and keeping just last 2 years?

### ISSUE THREAD

**Issue by nikmart** [hci-calendar/hci-calendar.github.io#12]
Hi there!

Thank you for putting this page together. I am happy to help update. Wondering if it might make sense to remove older years (say anything more that 2 years old) to keep the page shorter?

**Comment by masaogata** [comment]
Thank you for your help!
I planned to update the program to ignore older years but haven't yet.
Editing data files is the easiest solution I guess.

How about commenting out all but latest two years?
I still want to keep old information for estimating conference cycle.

**Comment by nikmart** [comment]
yeah, that sounds like a decent idea. The last 2 years should be enough.

**Comment by masaogata** [comment]
After half of the year, finally updated the program to show only the last two years.
Thank you!
